@startuml



:Usuário: as U


U -up-> (Cadastrar)
U --left--> (Logar)
U ----> (Adicionar informações)
U ----> (Pesquisar amigos)
U ----> (Adicionar amigo)
U ---down---> (Trocar mensagens privadas com amigo)
U ------> (Visualizar histórico de mensagens)
U --right--> (Desazer amizade)
U ----> (Publicar textos com no máximo 140 caracteres)
U ----> (Permitir que o texto publicado seja privado ou público)
U ----> (Realizar buscas acerca de viagens, restaurantes ou outros pontos da cidade)




@enduml
